#!/bin/bash

[ "$DEBUG" == 'true' ] && set -x

if [ -z ${ZKHOSTS+x} ]; then
	echo ZKHOSTS is not set 
	exit 1
fi

if [ -z ${SOLR_PORT+x} ]; then
	echo SOLR_PORT is not set 
	exit 1
fi

solr start -c -f -z $ZKHOSTS -p $SOLR_PORT